#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

caddy_bin="/usr/bin/caddy"
caddy_conf="/etc/caddy/Caddyfile"

start_service() {
	[ -x "$caddy_bin" ] || exit 1

	procd_open_instance
	procd_set_param command $caddy_bin run --config $caddy_conf
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	[ -x "$caddy_bin" ] || exit 1

	$caddy_bin reload --config $caddy_conf
}
